default_language_version:
  python: python3.8
default_stages:
  - commit
exclude: |
  (?x)^(
    | poetry\.lock
    | package-lock\.json
    | migrations\/.*
    | \.bumpversion\.cfg
    | whitelist\.py
    | \.idea\/.*
    | tests\/TESTS\.md
    | \.github\/COMMIT_POLICY\.md
    | docs\/conf\.py
    | Cargo\.lock
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
        exclude: ^(.*\.rs)$
      - id: check-merge-conflict
        exclude: ^(.*\.rst)$
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
        exclude: ^(.*test\.key)$
      - id: forbid-submodules
      - id: no-commit-to-branch
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args:
          - "--autofix"
      - id: fix-encoding-pragma
        args:
          - "--remove"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier
        args:
          - "--write"
  - repo: https://github.com/pappasam/toml-sort
    rev: "v0.23.1"
    hooks:
      - id: toml-sort
        args:
          - "--in-place"
          - "--all"
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/pre-commit/pre-commit
    rev: "v3.3.3"
    hooks:
      - id: validate_manifest
  - repo: https://github.com/siderolabs/conform
    rev: "v0.1.0-alpha.27"
    hooks:
      - id: conform
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.32.0"
    hooks:
      - id: yamllint
        args:
          - "--config-data={rules: {line-length: {max: 79}}}"
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
