version: "3.8"

services:
  rust-playground:
    image: hin-rust-playground
    build: .
    entrypoint: /opt/entrypoint
    command: tail -f /dev/null
    volumes:
      - ./src:/opt/hin/src
      - ./Cargo.toml:/opt/hin/Cargo.toml
      - ./Cargo.lock:/opt/hin/Cargo.lock
