pub mod add;
pub mod clone;
pub mod commit;
pub mod config;
pub mod files;
pub mod git;
pub mod gitignore;
pub mod install;
pub mod link;
pub mod list;
pub mod misc;
pub mod parser;
pub mod push;
pub mod remove;
pub mod status;
pub mod undo;
pub mod uninstall;

pub const NAME: &str = "hin";
pub const DOTFILES: &str = "DOTFILES";
